from fastapi import FastAPI, File, UploadFile, Form
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import pytesseract
from PIL import Image
import io
import os
from dotenv import load_dotenv

# ✅ NEW: Google GenAI SDK (latest)
from google import genai
from google.genai import types

# ----------------------------------------
# ✅ Initialize FastAPI app
# ----------------------------------------
app = FastAPI()

origins = ["http://localhost:3000", "http://127.0.0.1:3000"]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/healthz")
def health_check():
    return {"ok": True}

# ----------------------------------------
# ✅ Configure Gemini (Google AI Studio API key)
# ----------------------------------------
load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
if not GEMINI_API_KEY:
    raise RuntimeError(
        "Missing GEMINI_API_KEY. Put it in your environment or .env file."
    )

# Choose model: gemini-3-pro-preview (quality) or gemini-3-flash-preview (speed/cost)
MODEL_ID = os.getenv("GEMINI_MODEL", "gemini-3-flash-preview")

client = genai.Client(api_key=GEMINI_API_KEY)

# Optional generation settings (tune as needed)
GEN_CONFIG = types.GenerateContentConfig(
    temperature=0.2,
    max_output_tokens=8192,
    # If you want faster responses, uncomment the thinking_config:
    # thinking_config=types.ThinkingConfig(thinking_level="low"),
)

# ----------------------------------------
# 🧠 Session memory (for ongoing chat)
# ----------------------------------------
sessions = {}  # store conversation per user_id (simple in-memory store)

# ----------------------------------------
# ✅ OCR endpoint
# ----------------------------------------
@app.post("/extract-text")
async def extract_text(file: UploadFile = File(...)):
    contents = await file.read()
    image = Image.open(io.BytesIO(contents))
    text = pytesseract.image_to_string(image)
    return {"extracted_text": text}

# ----------------------------------------
# ✅ Upload new document and add to context
# ----------------------------------------
@app.post("/upload-doc")
async def upload_doc(user_id: str = Form(...), file: UploadFile = File(...)):
    contents = await file.read()
    image = Image.open(io.BytesIO(contents))
    text = pytesseract.image_to_string(image)

    prev_context = sessions.get(user_id, "")
    sessions[user_id] = prev_context + f"\n[New Document Extracted Text]:\n{text}\n"
    return {"message": "Document uploaded and added to your tax profile.", "extracted_text": text}

# ----------------------------------------
# ✅ Initial full AI tax analysis
# ----------------------------------------
class AnalyzePayload(BaseModel):
    text: str = ""
    user_id: str = "default"

@app.post("/analyze-text")
async def analyze_text(payload: AnalyzePayload):
    text = (payload.text or "").strip()
    user_id = payload.user_id or "default"

    if not text:
        return {"error": "No text provided"}

    prompt = f"""
STRICT OUTPUT RULES:
1) Output ONLY the Markdown report. No intro, no closing text, no extra commentary.
2) Use the EXACT headings and the EXACT order provided below. Do NOT add, remove, rename, or reorder headings.
3) Keep the exact table structures (same column names). Do NOT add extra columns.
4) If any value is missing/unclear from the extracted text, write [...] and do NOT guess or invent numbers.
5) Do NOT include any disclaimer, warning, legal note, or “consult a professional” type text.
6) Remove any occurrence of <br> from output.
7) Use ₹ for amounts. If a number is detected without commas, format it with Indian commas if possible (e.g., 1200000 → 12,00,000).
8) If the extracted text contains multiple documents (Form 16 + 26AS etc.), merge them and avoid duplicates.

You are a Certified Chartered Accountant (CA) and expert Indian tax consultant.
Analyze the extracted document text from Form 16, 26AS, AIS/TIS, bank interest certificates, or other financial records and generate a professionally formatted Markdown report.

## 🧾 Tax Summary (Auto-Generated by AI Tax Consultant)
✅ *PAN:* [Detected/Assumed]  
🏢 *Employer:* [Company Name]  
💰 *Total Income:* ₹[amount]  
💸 *Total TDS Detected:* ₹[amount]  
🏠 *House Property Income:* ₹[amount]  
🏦 *Interest Income:* ₹[amount]  
📊 *Gross Total Income:* ₹[amount]  
📉 *Deductions (80C, 80D, etc.):* ₹[amount or estimated]  
📈 *Taxable Income:* ₹[amount]  
🧾 *Suggested ITR Form:* [Form Number]  
📅 *Financial Year:* [FY/AY]  
⚙ *Computed Tax Liability:* ₹[amount]  
💡 *Remarks:* Professional summary in 2-3 lines.

---

## 💼 Step-by-Step Analysis
1. *Income Sources*
- Salary: ₹[…]
- Rent: ₹[…]
- Interest: ₹[…]
- Capital Gains: ₹[…]
- Other Income: ₹[…]

2. *TDS and Tax Deductions*
- Employer TDS: ₹[…]
- Bank/Other TDS: ₹[…]
- Total TDS: ₹[…]

3. *Deductions Identified (Section-wise)*
- 80C: ₹[…]
- 80D: ₹[…]
- 80CCD(1B): ₹[…]
- 80TTA/80TTB: ₹[…]
- Other: ₹[…]

4. *Final Tax Computation Table*

| Description | Amount (₹) |
|--------------|------------|
| Gross Income | […] |
| Deductions | […] |
| Taxable Income | […] |
| Tax Liability | […] |
| TDS Credited | […] |
| Net Payable / Refund | […] |

---

## 🧠 Tax Health & Risk Dashboard
| Metric | Score / Comment |
|--------|----------------|
| Refund Likelihood | [High / Medium / Low] |
| Notice Risk | [Low / Moderate / High] |
| Deduction Utilization | [%, comment] |
| Missing Sections | [80C, 80D, 80TTA, etc.] |
| Compliance Score | [0–100%] |

---

## 🧩 Insights & Recommendations
- Give 5–10 personalized, actionable recommendations.
- Mention missing proofs/documents to collect (if any).
- Suggest whether Old vs New regime seems better *based only on detected data*; if data is insufficient, write [...].

---

## 📊 Summary of All Extracted Data
| Field | Value |
|--------|--------|
| PAN | [...] |
| Employer | [...] |
| Assessment Year | [...] |
| Financial Year | [...] |
| Salary Income | [...] |
| House Property Income | [...] |
| Capital Gains | [...] |
| Interest Income | [...] |
| Other Income | [...] |
| Gross Total Income | [...] |
| Deductions (Total) | [...] |
| Taxable Income | [...] |
| Total TDS | [...] |
| Tax Liability | [...] |
| Net Payable / Refund | [...] |
| Suggested ITR Form | [...] |

---

Now analyze the extracted text below and generate the full Markdown report:

{text}
""".replace("<br>", "").strip()


    try:
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=prompt,
            config=GEN_CONFIG,
        )
        result = (response.text or "").replace("<br>", "")
        sessions[user_id] = result  # save this as base context
        return {"analysis": result}
    except Exception as e:
        return {"error": str(e)}

# ----------------------------------------
# ✅ Continue conversation with AI
# ----------------------------------------
@app.post("/chat")
async def chat_with_ai(user_id: str = Form(...), message: str = Form(...)):
    history = sessions.get(user_id, "")
    prompt = f"""
You are a professional Chartered Accountant AI.
Continue assisting the same user based on the previous context.

Conversation so far:
{history}

User says:
{message}

Update or refine the previous tax summary or give clarifications based on this.
""".strip()

    try:
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=prompt,
            config=GEN_CONFIG,
        )
        reply = (response.text or "").replace("<br>", "")
        sessions[user_id] = history + f"\nUser: {message}\nAI: {reply}\n"
        return {"reply": reply}
    except Exception as e:
        return {"error": str(e)}
